# Book settings
# template from https://github.com/executablebooks/github-action-demo
#Visto en:
#title: Inteligencia Artificial para las Ciencias e Ingenierías
#author: Raúl Ramos / Universidad de Antioquia
#logo: content/local/imgs/fudea.jpg

title: Tutorial de Tkinter
author: Juan Esteban Suarez / Universidad de Antioquia / Ingeniería eléctrica
logo: UdeA.png

repository:
   url: https://github.com/juan-suarezp/PythonTkinterTutorial
   branch: master

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

execute:
  execute_notebooks         : off
