# Book settings
# template from https://github.com/executablebooks/github-action-demo
#Visto en:
#title: Inteligencia Artificial para las Ciencias e Ingenierías
#author: Raúl Ramos / Universidad de Antioquia
#logo: content/local/imgs/fudea.jpg

title: Tutorial de Tkinter
author: Juan Esteban Suarez / Ingeniería eléctrica / Universidad de Antioquia
logo: logo.jpg

repository:
   url: https://github.com/juan-suarezp/Tk
   branch: master

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

execute:
  execute_notebooks         : off
